@RoomBookingApp_HostAddress = http://localhost:5037

POST {{RoomBookingApp_HostAddress}}/api/RoomBooking/checkAvailable
Accept: application/json
Content-Type: application/json

{"roomId": 1}
###

GET {{RoomBookingApp_HostAddress}}/api/Token/getToken


###
POST {{RoomBookingApp_HostAddress}}/api/Admin/login
Accept: application/json
Content-Type: application/json

{"UserName": "1", "Password": "1"}